Welcome to Free Pascal Testing Framework (FPTest)
=================================================

[abstract]
FPTest is a unit testing framework designed for Free Pascal projects, 
providing tools for writing and running tests.


This is a fork of the DUnit2 project and further adapted for use
with the Free Pascal Compiler and fpGUI Toolkit. The original code was
created by the late Peter McNab, who significantly enhanced DUnit2 with
excellent features, thoroughly tested using the extensive tiOPF test suite.

FPTest has a Text Test Runner and a GUI Test Runner (fpGUI Toolkit and
Lazarus Component Library versions).


Build Instructions
------------------

. Clone the https://github.com/graemeg/PasBuild[PasBuild] build
  automation tool, and install it according to its instructions. This is a once-off
  task.
. Then simply run the following command: `pasbuild compile`


Usage
-----
After you have built FPTest, point *your project* to FPTest's compiled units.
This usually means adding the `target/units` directory of your FPTest clone to
your compiler's unit search path.

* *FPC command line:* Add `-Fu/path/to/fptest/target/units` to your `fpc` command,
  replacing `/path/to/fptest` with the actual directory where you cloned FPTest.
* *In Lazarus IDE:* Go to Project -> Project Options -> Paths -> Other Unit Files, 
  and add the path to `$(FPTEST_DIR)/target/units` (where `$(FPTEST_DIR)` is the
  root directory of your FPTest clone).
* *In MSEide:* Go to Project -> Options -> Make -> Directories, and add the
  path to `$(FPTEST_DIR)/target/units` (where `$(FPTEST_DIR)` is the
  root directory of your FPTest clone). Then make sure the Unit column (U) is ticked.

And you're all good to go and ready to write those tests.


Writing Tests
-------------
Unit tests comprise of classes derived from TTestCase, each containing one
or more published test procedures as shown in the example below.

[code,pascal]
----
type
  TTestMyComms = class(TTestCase)
  published
    procedure VerifyThatThereIsAnUnAssignedCommPort;
    procedure VerifyThatTheCommPortOpens;
    procedure VerifyThatTheCommPortCloses;
  end;

...

initialization
  RegisterTests('Comms Tests', [TTestMyComms.Suite]);
----

Through the magic of RTTI, FPTest is able to execute the published test
procedures in an orderly fashion. Code written into test methods
performs tests on user's code, and calls one or more Check() procedures
to signal pass or fail to the test framework.

For more information about FPTest, have a look at the various documents
in the 'docs' directory.


Support
-------
Support can be found in the form of a newsgroup (NNTP Server) at:

  Server:  geldenhuys.co.uk
  Port:    119
  Group:   fptest.support

Those that can't use NNTP news client software for some reason, can
also access the support newsgroup via a web browser using the following
URL:

  http://geldenhuys.co.uk/webnews/


Brief History
-------------
As of July 2009, Graeme Geldenhuys decided to continue Peter's work
on DUnit2, but renamed the project to prevent confusion with the Delphi
based DUnit2 project hosted on SourceForge [which is a continuation of
Peter's work too]. The following ideas kicked off the FPTest development:

* No need for Delphi.NET support. The product doesn't exist anymore
  and .NET has its own testing framework anyway, called NUnit.
* Must work with the Free Pascal Compiler (FPC).
* Don't need Delphi support, because FPC is an excellent compiler.
* With FPC support comes the idea that it must be cross-platform
  friendly as well.
* Due to the previous item, removing the idea of writing to the Windows
  Registry is a logical step. Using something like INI, XML, or JSON config
  files will do a great job, are easy to edit, and works for all OSes.

